// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CT03EnviarMensagemTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT03EnviarMensagem() {
    driver.get("https://livros.inoveteste.com.br//contato");
    driver.findElement(By.name("your-name")).sendKeys("Jéssica Rodrigues");
    driver.findElement(By.name("your-email")).sendKeys("jessica@teste.com");
    driver.findElement(By.name("your-subject")).sendKeys("Curso Gratuito de selenium");
    driver.findElement(By.name("your-message")).sendKeys("Quais são os modulos desse curso?");
    driver.findElement(By.cssSelector(".wpcf7-submit")).click();
    try {
      Thread.sleep(15000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    assertThat(driver.findElement(By.cssSelector(".wpcf7-response-output")).getText(), is("Agradecemos a sua mensagem. Responderemos em breve."));
  }
}
