// Generated by Selenium IDE
package com.inove.tests;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class CT03EnviarMensagemTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private final String pathChromeDriver = "C:\\Program Files\\Selenium\\chromedriver.exe"; 
  
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", pathChromeDriver);    
//	System.setProperty("webdriver.chrome.whitelistedIps", pathChromeDriver);
    driver = new ChromeDriver();
	driver.manage().window().maximize();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @SuppressWarnings("deprecation")
  @Test
  public void cT03EnviarMensagem() {
    driver.get("https://livros.inoveteste.com.br//contato");
    driver.findElement(By.name("your-name")).sendKeys("Jéssica Rodrigues");
    driver.findElement(By.name("your-email")).sendKeys("jessica@teste.com");
    driver.findElement(By.name("your-subject")).sendKeys("Curso Gratuito de selenium");
    driver.findElement(By.name("your-message")).sendKeys("Quais são os modulos desse curso?");
    driver.findElement(By.cssSelector(".wpcf7-submit")).click();
    try {
      Thread.sleep(15000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    assertThat(driver.findElement(By.cssSelector(".wpcf7-response-output")).getText(),is("Agradecemos a sua mensagem. Responderemos em breve."));
  }
}
